"""Add missing tax columns

Revision ID: f80aa2a1f44c
Revises: 
Create Date: 2025-12-17 19:32:12.230275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80aa2a1f44c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_request', schema=None) as batch_op:
        batch_op.drop_column('tax1_data')
        batch_op.drop_column('tax2_data')

    with op.batch_alter_table('vendor_tax_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cert_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recipient_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('exemption_reason', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('section_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('threshold', sa.String(length=50), nullable=True))
        batch_op.alter_column('rate',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_tax_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('rate',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('threshold')
        batch_op.drop_column('section_code')
        batch_op.drop_column('exemption_reason')
        batch_op.drop_column('recipient_type')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('cert_no')

    with op.batch_alter_table('vendor_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax2_data', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tax1_data', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
